# Generated by Django 3.2.8 on 2021-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalProbabilities',
            fields=[
                ('arrivalProbId', models.IntegerField(primary_key=True, serialize=False)),
                ('binEdge', models.FloatField()),
                ('binEntry', models.FloatField(null=True)),
            ],
        ),
    ]
