# Generated by Django 3.2.8 on 2021-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundPower',
            fields=[
                ('BackgroundPowerId', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundProfiles',
            fields=[
                ('BackgroundId', models.IntegerField(primary_key=True, serialize=False)),
                ('BackgroundName', models.CharField(max_length=200)),
            ],
        ),
    ]
