# Generated by Django 3.2.8 on 2021-11-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgrounds',
            options={'ordering': ['Id']},
        ),
        migrations.AlterModelOptions(
            name='backgroundsets',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='BackgroundSetId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='simulation.backgroundsets'),
        ),
        migrations.AlterField(
            model_name='backgroundsets',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
