# Generated by Django 3.2.8 on 2021-10-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalprobabilities',
            options={'managed': False},
        ),
    ]
