# Generated by Django 3.2.8 on 2021-10-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_backgroundpower_backgroundprofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrivalprobabilities',
            old_name='arrivalProbId',
            new_name='ArrivalProbId',
        ),
        migrations.RenameField(
            model_name='arrivalprobabilities',
            old_name='binEdge',
            new_name='BinEdge',
        ),
        migrations.RenameField(
            model_name='arrivalprobabilities',
            old_name='binEntry',
            new_name='BinEntry',
        ),
    ]
