# Generated by Django 3.2.8 on 2021-10-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_alter_arrivalprobabilities_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrivalprobabilities',
            table='simulation_arrivalprobabilities',
        ),
    ]
