# Generated by Django 3.2.8 on 2021-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulationconfig_simulationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='houseId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
