# Generated by Django 3.2.8 on 2021-10-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_alter_arrivalprobabilities_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalprobabilities',
            options={},
        ),
    ]
