# Generated by Django 3.2.8 on 2021-10-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_alter_arrivalprobabilities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalprobabilities',
            options={'managed': False},
        ),
    ]
