# Generated by Django 3.2.8 on 2021-11-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_alter_arrivalprobabilities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalprobabilities',
            options={},
        ),
    ]
