# Generated by Django 3.2.8 on 2021-11-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_alter_arrivalprobabilities_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arrivalprobabilities',
            table=None,
        ),
    ]
