# Generated by Django 3.2.8 on 2021-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_alter_arrivalprobabilities_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingCurve',
            fields=[
                ('chargingCurveId', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
    ]
