# Generated by Django 3.2.8 on 2021-11-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_chargingcurve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrivalprobabilities',
            options={'ordering': ['arrivalProbId']},
        ),
        migrations.AlterModelOptions(
            name='chargingcurve',
            options={'ordering': ['chargingCurveId']},
        ),
    ]
