from django.shortcuts import render
from drf_multiple_model.views import ObjectMultipleModelAPIView
from rest_framework.response import Response
from simulation.models import *
from simulation.permissions import IsOwnerOrReadOnly
from simulation.serializers import *
from rest_framework import status
from rest_framework.views import APIView
from django.http import Http404
from rest_framework import mixins
from rest_framework import generics
from django.contrib.auth.models import User
from rest_framework import permissions
from simulation.permissions import IsOwnerOrReadOnly
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse
